### ISSUE TITLE
Breaking Change in v3.3.0

### ISSUE THREAD

**Issue by 0xTim** [swift-aws/aws-sdk-swift-core#122]
[This commit](https://github.com/swift-aws/aws-sdk-swift-core/commit/d25a9825a0a37cd1600730d3cbda1ccd1015d824#diff-261ff759bec063c130bbc9d2494243e9) introduced a breaking change in the Public API for the V4 Signer, so anyone running an update may see their code not compiling.

Not sure what the best way forward is but this is a break in SemVer so should at least be mentioned in the release notes I guess?

**Comment by adam-fowler** [comment]
I'll add something to the release notes. Not sure V4 Signer is really meant to be public. If you're using it to signURLs there is a new API in client to do that which is mentioned in the release notes.

**Comment by adam-fowler** [comment]
Updated release notes

**Comment by 0xTim** [comment]
Thanks!
