### ISSUE TITLE
consider depending on NIO using 'from:'

### ISSUE THREAD

**Issue by weissi** [swift-aws/aws-sdk-swift-core#128]
Right now, aws-sdk-swift-core depends on NIO with `.upToNextMinor`:

```
        .package(url: "https://github.com/apple/swift-nio.git", .upToNextMinor(from:"2.8.0")),
        .package(url: "https://github.com/apple/swift-nio-ssl.git", .upToNextMinor(from:"2.4.0")),
```

NIO follows SemVer [very strictly](https://github.com/apple/swift-nio/blob/master/docs/public-api.md) and if at all possible I would very much suggest to depend on NIO with `from: "2.8.0"` (or the equivalent `.upToNextMajor(from: "2.8.0")`).

It is very important for the ecosystem to depend on foundational libraries like SwiftNIO using up to next major because otherwise aws-sdk-swift-core will be incompatible with many packages.

Additionally, before every SwiftNIO release, we run our 'release tools' which test the compatibility with many packages and we can just add aws-sdk-swift-core so there's really no more risk using `from: "2.8.0"` instead of `.upToNextMinor(from: "2.8.0")`.

What were the considerations that lead to using  `.upToNextMinor(from: "2.8.0")`?

**Comment by adam-fowler** [comment]
ok, I can change to .upToNextMajor(). If you could include aws-sdk-swift-core in your compatibility tests that be great.

**Comment by weissi** [comment]
@adam-fowler thank you, consider it done :). Running the first run right now, if I find anything, I'll contact you

**Comment by weissi** [comment]
@adam-fowler done

```
- running 'git clone git@github.com:swift-aws/aws-sdk-swift-core.git' (log in '/tmp/.nio-release-tools_Sux8XC/log_git_haJCHO')
> OK 2s
- running 'swift package edit --path /tmp/.nio-release-tools_Sux8XC/swift-nio swift-nio' (log in '/tmp/.nio-release-tools_Sux8XC/log_swift_1kPPLs')
> OK 11s
- running 'swift package edit --path /tmp/.nio-release-tools_Sux8XC/swift-nio-ssl swift-nio-ssl' (log in '/tmp/.nio-release-tools_Sux8XC/log_swift_n4xpnR')
> OK 0s
- running 'swift test --disable-index-store' (log in '/tmp/.nio-release-tools_Sux8XC/log_swift_wDvsjO')
> OK 132s
- running 'run_in_docker swift test --disable-index-store' (log in '/tmp/.nio-release-tools_Sux8XC/log_run_in_docker_iE45Bh')
> OK 110s
- running 'swift test --sanitize=address --disable-index-store' (log in '/tmp/.nio-release-tools_Sux8XC/log_swift_jKWhFu')
> OK 34s
- running 'swift test --sanitize=thread --disable-index-store' (log in '/tmp/.nio-release-tools_Sux8XC/log_swift_3vzvvC')
> OK 139s
- running 'swift test --sanitize=address -c release -Xswiftc -enable-testing --disable-index-store' (log in '/tmp/.nio-release-tools_Sux8XC/log_swift_PEUvpI')
ERROR: swift failed
```

so everything passed but the tests don't run in release mode (#43), I'm going to not run the tests in release mode for the time being. Please let me know if you want me to enable running your tests in release mode again.

**Comment by adam-fowler** [comment]
This is something you brought up with aws-sdk-swift-core a wee while back #43. I wasn't part of the project at the time. I can discuss with the other guys to see if this is something we can change. In the meantime I guess don't run the release mode test.

**Comment by weissi** [comment]
> This is something you brought up with aws-sdk-swift-core a wee while back #43. I wasn't part of the project at the time. I can discuss with the other guys to see if this is something we can change. In the meantime I guess don't run the release mode test.

Sounds great! For now, I have in in the release tools suite and I run all tests on Linux & macOS with TSan & ASan (but not in release mode). Please ping me if you want me to change the test runner to also run the release mode tests.

**Comment by Yasumoto** [comment]
Thanks so much, folks! 🎉

**Comment by Yasumoto** [comment]
I think https://github.com/swift-aws/aws-sdk-swift-core/pull/134 should square this away.

**Comment by adam-fowler** [comment]
@weissi The tests now compile and run in release on head of aws-sdk-swift-core
