### ISSUE TITLE
Option to inject `EventLoopGroup` into `AWSClient`

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift-core#137]
**Describe the bug**
The `AWSClient` currently holds a static shared `EventLoopGroup` instance. 

```swift
public static let eventGroup: EventLoopGroup = createEventLoopGroup()
```

**Expected behavior**

As Cory Benfield [pointed out](https://forums.swift.org/t/how-to-wrap-the-initialization-ceremony-with-a-client/14541/2):

> Libraries should almost never choose to own their own EventLoopGroup. This is because it's highly valuable to have an extremely small number of groups in an application; in fact, for many applications you may want only one.

Therefore I would assume, one can have the chance to inject ones own `EventLoopGroup` into the `AWSClient`. Therefore I propose we add another property `eventLoopGroup` to the quite long initializer:

```swift
public init(accessKeyId: String? = nil, secretAccessKey: String? = nil, sessionToken: String? = nil, region givenRegion: Region?, amzTarget: String? = nil, service: String, signingName: String? = nil, serviceProtocol: ServiceProtocol, apiVersion: String, endpoint: String? = nil, serviceEndpoints: [String: String] = [:], partitionEndpoint: String? = nil, middlewares: [AWSServiceMiddleware] = [], possibleErrorTypes: [AWSErrorType.Type]? = nil)
```

**Additional context**

When thinking about solving this problem there are two possible implementation options:

1. The `eventLoopGroup` has a default value at initialization (the current `AWSClient.eventGroup`)
- **Pro**: Non breaking API Change
- **Con**: The style does not enforce minimizing the number of `EventLoopGroup`s.
2. The `eventLoopGroup` must be provided at initialization
- **Pro**: The style does enforce minimizing the number of `EventLoopGroup`s. 
- **Pro**: The shared instance `AWSClient.eventGroup` could be removed.
- **Con**: A breaking API Change

**Personal opinion**

Since a 4.0.0 release is around the corner, we could go for the breaking API change. I think that a library as important as `aws-sdk-swift` should embrace using as few `EventLoopGroup`s as possible. But I could understand, if such a big API breaking change is not intended for now.

However the maintainers decide, I would be more than happy to provide a PR for this.

**Comment by fabianfett** [comment]
Also this change would make it much easier to use the `AsyncHTTPClient` in the future if wanted.

**Comment by adam-fowler** [comment]
Yep that's been on the list of things todo for a while. Probably go for something similar to async-http-client's eventLoopGroupProvider enum, although I'd rather we didn't create new eventLoopGroups, just choose between AWSClient's static one or the one provided in the enum. As AWSClient's static version is lazy initialised it should never be created if the user passes their own.

Not giving the parameter a default value would make people consider what they want to do. This would be breaking API change. Not sure what the other guys would think about that @Yasumoto @jonnymacs

**Comment by Yasumoto** [comment]
Totally think we should follow the `eventLoopGroupProvider` enum pattern before cutting a final `4.0.0`.

**Comment by fabianfett** [comment]
PR landed. Issue is resolved. Close.
