### ISSUE TITLE
Use `AsyncHTTPClient` package as a replacement for `HTTPClient`

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift-core#138]
**Is your feature request related to a problem? Please describe.**
Following the programmers principle: "The less code I write, the less bugs I produce", I think it would be great to switch the internal implementation to remove the `HTTPClient` and use the [`AsyncHTTPClient`](https://github.com/swift-server/async-http-client) package instead.

**Describe the solution you'd like**
Depend on the [`AsyncHTTPClient`](https://github.com/swift-server/async-http-client) and use it in the `AWSClient`.

**Describe alternatives you've considered**
Everything stays as is.

**Additional context**
Further it should be investigated, if it makes sense to keep one `HTTPClient` in the `AWSClient` around (as a property). Currently with each request a new `HTTPClient` is created. Even if the `HTTPClient` would support connection-pooling the `AWSClient` currently would not make any use of this.

Since [the SSWG has mentioned that they are working on connection-pooling](https://swift.org/blog/sswg-update/) for the [`AsyncHTTPClient`](https://github.com/swift-server/async-http-client), I propose, that a changed implementation of the `AWSClient` initializes it's `HTTPClient` in the init and keeps the `HTTPClient` around for its lifetime.

> Vapor’s AsyncKit package, AsyncHTTPClient, and others are working on connection pool implementations. There are lots of interesting questions coming up already around concurrency and performance. Can there be one connection pool to rule them all, or should there be many separate ones that follow well considered best practices? If you have ideas on how connection pooling in Swift should work, let’s combine forces.

If the maintainers are okay with this I would like to try my best to provide a PR.

**Comment by adam-fowler** [comment]
I have looked into this and I have had a build running using it but this would break builds using nio-transport-services ie iOS and macOS (although we could use NIOSSL for macOS). I have looked at the option of using async-http-client when not linking with nio-transport-services. Not overly keen on the diverging code paths between macOS and Linux though but think this is a probably going to have to happen at least with iOS.

Regarding the HTTPClient being initialised once, there is one issue if you do this. You need to call HTTPClient.syncShutdown() before you destroy an HTTPClient. This will need to be done for the HTTPClient inside the AWSClient. Will we require users to call an equivalent AWSClient.syncShutdown()?

**Comment by fabianfett** [comment]
> I have looked into this and I have had a build running using it but this would break builds using nio-transport-services ie iOS and macOS (although we could use NIOSSL for macOS). I have looked at the option of using async-http-client when not linking with nio-transport-services. Not overly keen on the diverging code paths between macOS and Linux though but think this is a probably going to have to happen at least with iOS.

I think we can completely hide the HTTPClient implementation from the user. I would assume that the `async-http-client` should also support `nio-transport-services` sooner or later. 

I asked in the #async-http-client channel in the [swift-server slack](http://swift-server.slack.com/):

> Not sure if this a completely stupid question, but is there a plan to use swift-nio-transport-services as the underlying framework for the async-http-client on Darwin?

[Artem Redkin](https://github.com/swift-server/async-http-client/graphs/contributors) replied:

> hi! completely not a stupid question, we don't have immediate plans to add this, but it's on our radar, just want to concentrate on connection pool first

For the time being we could use the current `AWSClient.HTTPClient` on Darwin and use the `async-http-client` on Linux. When the time comes for `async-http-client` to support Darwin as well we could switch completely. But I'm quite sure, that using the `async-http-client` will benefit this package in the long run.

> Regarding the HTTPClient being initialised once, there is one issue if you do this. You need to call HTTPClient.syncShutdown() before you destroy an HTTPClient. This will need to be done for the HTTPClient inside the AWSClient. Will we require users to call an equivalent AWSClient.syncShutdown()?

Yes. I guess, that this methods was created to end any running operation. In a normal server use-case I would guess that the AWSClient is created at server bootup and destroyed on shutdown. Creating a client for every request should IMHO be seen as an antipattern (for connection pooling reasons). 

Currently this method is called on every invoke. Especially the naming of `sync` and running this in the EventLoop should be a big nono. Sadly there is [no async option at the moment](https://github.com/swift-server/async-http-client/issues/126).

```swift
    fileprivate func invoke(_ nioRequest: HTTPClient.Request) -> Future<HTTPClient.Response> {
        let client = HTTPClient(eventLoopGroupProvider: .shared(AWSClient.eventGroup))
        let futureResponse = client.connect(nioRequest)

        futureResponse.whenComplete { _ in
            do {
                try client.syncShutdown()
            } catch {
                print("Error closing connection: \(error)")
            }
        }

        return futureResponse
    }
```

But if we are going forward to make this change, we should consider the following: Right now every AWS Service has its own facade (which is awesome). The facade creates its own AWSClient and uses that one. Maybe we should consider creating an AWSClient only with credentials and the region. Then we could inject this client into every service facade. The service facade would then inject all the other information (`amzTarget`, `service`, `serviceProtocol`, `apiVersion`, `endpoint`, `middlewares`, `possibleErrorTypes`) for every call. This way we could use a single AWSClient basically for all service facades within one region and we would only need to call syncShutdown once.

```swift
public struct ECS {

    public let client: AWSClient

    public init(accessKeyId: String? = nil, secretAccessKey: String? = nil, sessionToken: String? = nil, region: AWSSDKSwiftCore.Region? = nil, endpoint: String? = nil, middlewares: [AWSServiceMiddleware] = []) {
        self.client = AWSClient(
            accessKeyId: accessKeyId,
            secretAccessKey: secretAccessKey,
            sessionToken: sessionToken,
            region: region,
            amzTarget: "AmazonEC2ContainerServiceV20141113",
            service: "ecs",
            serviceProtocol: ServiceProtocol(type: .json, version: ServiceProtocol.Version(major: 1, minor: 1)),
            apiVersion: "2014-11-13",
            endpoint: endpoint,
            middlewares: middlewares,
            possibleErrorTypes: [ECSErrorType.self]
        )
    }

    ///  Creates a new Amazon ECS cluster. By default, your account receives a default cluster when you launch your first container instance. However, you can create your own cluster with a unique name with the CreateCluster action.  When you call the CreateCluster API operation, Amazon ECS attempts to create the service-linked role for your account so that required resources in other AWS services can be managed on your behalf. However, if the IAM user that makes the call does not have permissions to create the service-linked role, it is not created. For more information, see Using Service-Linked Roles for Amazon ECS in the Amazon Elastic Container Service Developer Guide. 
    public func createCluster(_ input: CreateClusterRequest) -> Future<CreateClusterResponse> {
        return client.send(operation: "CreateCluster", path: "/", httpMethod: "POST", input: input)
    }

    ...
}
```

**Comment by adam-fowler** [comment]
I don't think we can rely on a nio transport services version of async http client appearing in the near future. I had a look at doing my own version a month back and gave up. Trying to keep both TS and NIOSSL versions together and making them readable was very trying. I gave up.

Regarding the creation/deletion of HTTPClient (in both the aws-sdk-swift-core and the async-http-client versions). The syncShutdown() is basically there to shutdown the eventLoopGroup. If you initialise them with a shared eventLoopGroup, the initialiser and syncShutdown basically don't do anything. So creating and deleting them isn't that much of an issue. Of course this is reliant on implementation details.

**Comment by fabianfett** [comment]
Just for reference. https://github.com/swift-server/async-http-client/issues/127

> I don't think we can rely on a nio transport services version of async http client appearing in the near future. I had a look at doing my own version a month back and gave up. Trying to keep both TS and NIOSSL versions together and making them readable was very trying. I gave up.

Well that way code should become even more readable if we just have an `NIOTSClient` for `Darwin` 😉

Would it make sense to put your already done work in a Draft Pull Request?

**Comment by adam-fowler** [comment]
I'll go find it

**Comment by adam-fowler** [comment]
Found old code and rewrote to include the HTTPClient selection #141

**Comment by adam-fowler** [comment]
done
