### ISSUE TITLE
Need to review Hypertext application language processing

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#142]
This hasn't been updated to work with EventLoopFutures. It does some nasty stuff when it needs to load link map entries. It stalls in a while loop repeatedly sending requests to the http client while polling to see if the request has succeeded.

Haven't found any AWS services that actually require the loading of link map entries so it's kinda hard to test any fixes.

**Comment by fabianfett** [comment]
> Haven't found any AWS services that actually require the loading of link map entries so it's kinda hard to test any fixes.

May I ask what is it used for then?

**Comment by adam-fowler** [comment]
There are 200 odd aws services. The fact that I haven’t found one doesn’t mean it doesn’t exist. @jonnymacs may have a better idea but he didn't seem to last time we spoke about it. 

The HAL stuff was implemented for some reason and Hal+Json is returned by some services eg apigateway. It just seems it doesn’t provide any extra data we need to decide a response.

**Comment by adam-fowler** [comment]
Just did a search in aws-sdk-go and aws-sdk-js repositories for ‘hypertext application language’ and ‘hal+json’. Neither of these keywords come up. I’m wondering if we need this code at all.

**Comment by adam-fowler** [comment]
Verified we do need some of the HAL support as the api response is hidden inside the Hal json.

**Comment by adam-fowler** [comment]
fixed in #163
