### ISSUE TITLE
Switch HMAC implementation to SwiftNIO's BoringSSL?

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift-core#143]
**Is your feature request related to a problem? Please describe.** 
As we all know SwiftNIO switched its underlying TLS implementation from [OpenSSL and LibreSSL to BoringSSL](https://forums.swift.org/t/rfc-moving-swiftnio-ssl-to-boringssl/18280). Thanks to this change OpenSSL doesn't have to be installed on Linux machines that host SwiftNIO servers. Since `aws-sdk-swift-core` still uses `OpenSSL` for creating the HMAC on Linux I propose the following:

**Describe the solution you'd like**
Instead of linking against OpenSSL, I would add a dependency to `swift-nio-ssl` on non `Darwin` systems and import the `CNIOBoringSSL` library. This dependency is probably loaded anyway since the `AsyncHTTPClient` will use it as well. We could then drop the `CAWSSDKOpenSSL` target.

**Describe alternatives you've considered**
Everything stays as is.

**Additional context**
Having as few dependencies on the hosting system as possible will make `aws-sdk-swift` more approachable for more users.

If the maintainers think this is something worth investigating I would be more than happy to look into this and build up a pr.

**Comment by adam-fowler** [comment]
Swift NIO’s version of BoringSSL is considered internal to nio and we’ve been told we shouldn’t use it. 

Can’t find the related link at the moment, but here is

**Comment by fabianfett** [comment]
Okay. I didn’t know that.
To bad. I would really like to get the OpenSSL dependency out. But I’ll close the issue for now.

**Comment by adam-fowler** [comment]
Oh god I've been trying to get rid of it in various ways. Don't need it on mac or iOS but Linux there is currently no other option. I would prefer something that was cross platform as the current solution has different setups for Linux and the apple OS's

**Comment by fabianfett** [comment]
Would it be an option to just copy and paste the hmac implementation from https://github.com/krzyzanowskim/CryptoSwift. I would just compile it if CommonCrypto is not available. But we would get rid of OpenSSL.

**Comment by adam-fowler** [comment]
Not sure replacing C versions of crypto functions with swift versions is very sensible from a performance point of view.

**Comment by Yasumoto** [comment]
Took me a bit, but here's the convo about not depending on `BoringSSL` from within NIO:

https://github.com/swift-aws/aws-sdk-swift-core/pull/72#discussion_r314334006
