### ISSUE TITLE
Support Instance Metadata v2

### ISSUE THREAD

**Issue by Yasumoto** [swift-aws/aws-sdk-swift-core#148]
AWS [just announced](https://aws.amazon.com/about-aws/whats-new/2019/11/announcing-updates-amazon-ec2-instance-metadata-service/) there's a new, session-based Metadata Service API.

Implementation details [in the EC2 User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#configuring-instance-metadata-service).

**Comment by adam-fowler** [comment]
Looks like we should be careful implementing this. Even AWS are getting this wrong. https://github.com/aws/aws-cli/issues/4682

**Comment by adam-fowler** [comment]
done in #184
