### ISSUE TITLE
Add support for retrying failed requests

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#152]
Add support for retrying failed requests. Retry on 5xx errors, throttling errors (429) and connection errors. Wait times between retries should increase exponentially with added random jitter. 

Create a retry object that indicates whether a retry should occur (based on error occurring, or status code returned), the time between retries and the number of retries attempted.

Each AWSClient will have an instance of one of these objects, which can be overriden at initialisation.

**Additional context**
Here is details from amazon https://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by Yasumoto** [comment]
So long as we provide a way to disable the retries, sounds great!

**Comment by adam-fowler** [comment]
> So long as we provide a way to disable the retries, sounds great!

The client can be initialised with a retry object that does no retries
