### ISSUE TITLE
MetaDataService Hangs trying to retrieve credentials - Version 3.4.0

### ISSUE THREAD

**Issue by dashadrick** [swift-aws/aws-sdk-swift-core#153]
**Describe the bug**
Developed a solution designed to rely on EC2 MetaDataService and IAM Roles and Policies for credentials.  AWS client on the EC2 instance is configured with just region and no keys. The AWS client is able to access the necessary AWS services using the IAM Role and Policies I've configured. The aws metadata service is return the roles keys and token.

Code works on local machine where we rely on the aws config on the local machine, but when I try to use AWSSDKSwift to access the same resources on the server using the MetaDataService the process hangs.  

**To Reproduce**
Setup EC2 server without storing aws secret keys in the aws config and force the use of the MetaDataService.  

**Expected behavior**
Expect to work as smoothly as it does on the local machines.

***This change allows the code to run as expected***
Commenting out the following code in (MetaDataService.swift line 101) keeps the process from hanging and allows my code to run as expected:

    static func request(host: String, uri: String, timeout: TimeInterval) -> Future<HTTPClient.Response> {
        let client = HTTPClient(hostname: host, port: 80)
        let head = HTTPRequestHead(
                     version: HTTPVersion(major: 1, minor: 1),
                     method: .GET,
                     uri: uri
                   )
        let request = HTTPClient.Request(head: head, body: Data())
        let futureResponse = client.connect(request)
        /*
        futureResponse.whenComplete {
            client.close { error in
                if let error = error {
                    print("Error closing connection: \(error)")
                }
            }
        }
        */
        return futureResponse
    }
Also, though no impact, line 66 has an extra "/" 

    return "\(self.baseURLString)/\(roleName)"

that produces the following URL:

    http://169.254.169.254/latest/meta-data/iam/security-credentials//roleName

**Setup (please complete the following information):**
 - OS: ubuntu:18.04 Swift:5.1
 - Version of aws-sdk-swift : 3.4.0 
 - Authentication mechanism IAM Instance Profile on EC2

**Comment by adam-fowler** [comment]
Commenting out the `whenComplete()` would cause a memory leak. The MetaDataService has had a refactor on the master branch (4.x.x). Not sure why this would break now though this code has been running for quite some time without issue.

Let me investigate

**Comment by adam-fowler** [comment]
Not sure why this was broke. Something seems to have changed underneath as it was working before. Anyway I have fixed it by removing the constant creation/deletion of `EventGroupLoops` which we have already removed in 4.0 already. This fix is available on the 3.x.x branch and will be in a release in the near future
