### ISSUE TITLE
Remove Foundation.Data from Body

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift-core#161]
**Is your feature request related to a problem? Please describe.**
Body currently uses `Foundation.Data`. We should try to use NIO.ByteBuffer internally as much as possible to reduce the number of copies. 

**Describe the solution you'd like**
Replace `Foundation.Data` with `NIO.ByteBuffer` in `Body`.

**Describe alternatives you've considered**
Everything stays as is.

**Additional context**
This was something that came up while reviewing the `AsyncHTTPRequest` branch.

**Comment by adam-fowler** [comment]
Make sure we aren't converting back to `Data` at any point. Both S3 and Glacier middleware access the request body as `Data`

**Comment by adam-fowler** [comment]
Question: Should we replace all the `Data` objects in the input/output shapes with `ByteBuffer`?

**Comment by adam-fowler** [comment]
Can we close this now?
