### ISSUE TITLE
Initialise AWS client with HTTPClient

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#165]
Allow user to pass in HTTPClient to AWSClient.init() and use that for all http calls. This would allow the user to pass in an HTTPClient configured as they like. Perhaps they have a proxy to configure.

If we use the AWSHTTPClient protocol defined in the async-http-client branch they could use their own client as long as it conforms to the AWSHTTPClient.

This does beg the question do we need to pass in an eventLoopGroupProvider if we allow the user to provide the HTTP client as the eventLoopGroup is only ever used in conjunction with the HTTPClient or to provide succeeded/failed futures? I'm guessing we could support both but providing both at the same time would be an invalid operation.

**Comment by fabianfett** [comment]
I would love that! Probably something for 5.0.

**Comment by fabianfett** [comment]
> This does beg the question do we need to pass in an eventLoopGroupProvider if we allow the user to provide the HTTP client as the eventLoopGroup is only ever used in conjunction with the HTTPClient or to provide succeeded/failed futures? I'm guessing we could support both but providing both at the same time would be an invalid operation.

I'm not sure if we should compromise on this point: I came to `aws-sdk-swift` because it is undoubtedly a `swift-nio` based framework. I can see the benefits of giving users more flexibility but I'm afraid this would be at the costs of its server side focus.

**Comment by adam-fowler** [comment]
> I'm not sure if we should compromise on this point: I came to `aws-sdk-swift` because it is undoubtedly a `swift-nio` based framework. I can see the benefits of giving users more flexibility but I'm afraid this would be at the costs of its server side focus.

The reason I mention not passing in an eventLoopGroupProvider is the only situation we use the eventLoopGroup is as part of the HttpClient. If we are supplying the HttpClient it can setup it's own eventLoopGroup. And the one we pass into AWSClient isn't used for anything.

**Comment by fabianfett** [comment]
Oh true. My bad. That is very true. In favor!

**Comment by fabianfett** [comment]
Question would be than though how would we implement an `AWSHTTPClient` based on `URLSession` that emits `EventLoopFuture`s. To be honest this sounds more like an intellectual challenge than something at least I would use.
