### ISSUE TITLE
Should we support swift-log and swift-metrics

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#166]
There is a push for many swift server libraries to integrate with standard swift server components like swift-log and swift-metrics. Do we want to do this?

We already have a AWSLoggingMiddleware() but that just has a callback to deal with logging information and there is no logging level. We could change this to take a `Logger` and provide some level of control over what is output instead.

If we were to integrate swift metrics what would we want to measure? Errors, response time?

Do we want more dependencies on this project?

**Comment by fabianfett** [comment]
If we want to ensure `aws-sdk-swift` is also a good citizen on iOS, we should be really careful here.

**Comment by adam-fowler** [comment]
> If we want to ensure `aws-sdk-swift` is also a good citizen on iOS, we should be really careful here.

good point

**Comment by Yasumoto** [comment]
Would love to see support for [`RED` metrics (Requests, Error Rate, Duration)](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/) to track each request we send.

**Comment by adam-fowler** [comment]
@Yasumoto PR #245 implements RED metrics
