### ISSUE TITLE
Provide URLSession based HTTPClient for iOS

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#167]
URLSession has special entitlements on iOS. It runs in the background so downloads can run while apps are minimised. We should provide access to this through an HTTPClient that utilises URLSession. 

This is reliant on #165

**Comment by fabianfett** [comment]
> URLSession has special entitlements on iOS. It runs in the background so downloads can run while apps are minimised.

This will be super hard to implement in a library, since the `NSURLSessionTask`s taskId needs to be persisted between calls. Only use case I can come up is downloading from and uploading to s3. This is already implemented by AWS: https://aws.amazon.com/blogs/mobile/amazon-s3-transfer-utility-for-ios/

**Comment by adam-fowler** [comment]
> This will be super hard to implement in a library, since the `NSURLSessionTask`s taskId needs to be persisted between calls. Only use case I can come up is downloading from and uploading to s3. This is already implemented by AWS: https://aws.amazon.com/blogs/mobile/amazon-s3-transfer-utility-for-ios/

If user is providing HTTPClient (a la #165) the `NSURLSessionTask` taskId can persist in the HTTPClient. Don't think this is a huge requirement but if we are providing HTTPClient to aws-swift-sdk this makes this quite possible.

**Comment by fabianfett** [comment]
> If user is providing HTTPClient (a la #165) the NSURLSessionTask taskId can persist in the HTTPClient. Don't think this is a huge requirement but if we are providing HTTPClient to aws-swift-sdk this makes this quite possible.

But the complete callbacks are gone. BackgroundSession can not be implemented like "normal" URLSessions and they IMHO make only sense for downloads and uploads.

**Comment by adam-fowler** [comment]
> But the complete callbacks are gone. BackgroundSession can not be implemented like "normal" URLSessions and they IMHO make only sense for downloads and uploads.

I was under the impression the complete callbacks were still called, but only when you bring your app to the front again.

**Comment by fabianfett** [comment]
> I was under the impression the complete callbacks were still called, but only when you bring your app to the front again.

That would be so awesome. Sadly this is not the case and I have cried many, many tears about this. 

With background sessions you can’t assume that your app is just in inactive state. It might be terminated completely.
