### ISSUE TITLE
Evaluate use of MaxDesiatov/XMLCoder

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift-core#180]
For the XML parsing, we should IMHO evaluate the use of @MaxDesiatov's [XMLCoder](https://github.com/MaxDesiatov/XMLCoder).

What are your opinions?

**Comment by MaxDesiatov** [comment]
Great to see that my library is considered, please let me know if I can help in any way in terms of bugfixes/documentation/platform support etc 🙏

**Comment by adam-fowler** [comment]
Things to consider:
- What are we gaining here?
- We need a XML Node format we can navigate. XMLCoder seems to return Foundation.Data
- We need to define collection (array, dictionary) encoding on a per shape member basis. eg
Arrays can be encoded in the following 2 ways
```<array>...</array><array>...</array><array>...</array>```
```<array><member>...</member><member>...</member><member>...</member></array>```
with array element being name of array. The member element is not necessarily called "member"
Dictionaries can be encoded in the following 2 ways
```<dictionary><key>...</key><value>...</value><key>...</key><value>...</value></dictionary>```
```<dictionary><entry><key>...</key><value>...</value></entry><entry><key>...</key><value>...</value></entry></dictionary>```
with dictionary element being the name of the dictionary. The entry, key and value elements can all have different names as well.

**Comment by fabianfett** [comment]
@adam-fowler can you point me to a service that uses the xml representation so that i can have a look at it?

**Comment by adam-fowler** [comment]
> @adam-fowler can you point me to a service that uses the xml representation so that i can have a look at it?

S3 and CloudFront are xml services. SNS and IAM are query services which respond with XML.

**Comment by adam-fowler** [comment]
With the codable property wrapper work in #215 the collection encoding point is not an issue.

**Comment by adam-fowler** [comment]
Had a look at the performance of both of the xml encoder/decoders. Max's is about 2 times slower. Also it wasn't decoding the Dictionaries correctly. I'm gonna close this now
