### ISSUE TITLE
Add Payload object for Data blobs

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#185]
Add a `Payload` shape to support both `Foundation.Data` and `NIO.ByteBuffer` for data storage in AWSShapes. Use this for any Foundation.Data that is also flagged as the payload for a request or response. eg `S3.PutObject`. This would allow us to pass data from one command response to another without having to convert to `Foundation.Data` and back to `NIO.ByteBuffer`, while still allowing people to use `Data.Foundation`.
```
enum Payload {
    case .data(Data)
    case .byteBuffer(ByteBuffer)
    case .empty
}
```
The main thing that complicates implementing this is ByteBuffer does not comply with Codable. We would have to jump through some hoops to get response decoding working correctly to insert the payload into the response struct. Request encoding should be ok as we shouldn't need to encode the payload as we are outputting a raw data body.

**Comment by adam-fowler** [comment]
We could implement this for Request shapes without doing the Response shapes initially.

**Comment by adam-fowler** [comment]
This came up when I was looking at using NIONonBlockingFileIO which returns a ByteBuffer, which at the moment I would have to convert to Data before passing to aws-sdk-swift.

**Comment by adam-fowler** [comment]
We could extend this to include streamed data. 
```
enum Payload {
    case stream(()->EventLoopFuture<ByteBuffer>)
    ...
}
```

**Comment by bridger** [comment]
Channels can also send data from a file directly to a socket without loading the file into memory. The type that supports this is `FileRegion`. It would be awesome to be able to upload using that.

**Comment by adam-fowler** [comment]
> Channels can also send data from a file directly to a socket without loading the file into memory. The type that supports this is `FileRegion`. It would be awesome to be able to upload using that.

I’ll have a look into this but we would need AsyncHTTPClient to support this, which as of this point in time it doesn’t.
