### ISSUE TITLE
Allow AWSClient Region to be configured with an arbitrary string

### ISSUE THREAD

**Issue by clenart** [swift-aws/aws-sdk-swift-core#226]
**Is your feature request related to a problem? Please describe.**
When interacting with non-AWS services which provide an implementation of an AWS API, it can be necessary to configure a Region string for V4 signing, which is not in the set of Regions that AWS provides.

**Describe the solution you'd like**
While the Region enum is user friendly and what 99% of clients will likely need, it would be useful to represent the Region internally as a String. And provide an init or setter method, which allows the Region to be set as any arbitrary string.

**Describe alternatives you've considered**
I'm not sure there is any other way to handle it. If arbitrary strings are not allowed in the V4 Region name, then this library cannot interact with other cloud providers who implement AWS APIs (S3 API being the most popular, for example).

**Additional context**

**Comment by adam-fowler** [comment]
Which cloud providers are you thinking?
