### ISSUE TITLE
Dependencies prevent building apps with Vapor, Perfect, Kitura, etc.

### ISSUE THREAD

**Issue by sdnakhla** [swift-aws/aws-sdk-swift-core#25]
Some of the aws-sdk-swift-core dependencies (Prorsum, I believe) are causing build issues when trying to build a Swift project with aws-sdk-swift and server-side frameworks such as Vapor, Perfect, Kitura, etc.  When building with Vapor, I see this error:

> 'HTTP' /Volumes/Untitled/SwiftDev/MyApp/.build/checkouts/http.git-9159899851620770205: error: multiple targets named 'Performance'

With Perfect, I get multiple error messages that look like this:

> duplicate symbol _http_parser_pause in:
>     /Volumes/Untitled/SwiftDev/MyApp/.build/x86_64-apple-macosx10.10/debug/CHTTPParser.build/http_parser.c.o
>     /Volumes/Untitled/SwiftDev/MyApp/.build/x86_64-apple-macosx10.10/debug/PerfectCHTTPParser.build/http_parser.c.o
> duplicate symbol _http_errno_name in:
>     /Volumes/Untitled/SwiftDev/MyApp/.build/x86_64-apple-macosx10.10/debug/CHTTPParser.build/http_parser.c.o
>     /Volumes/Untitled/SwiftDev/MyApp/.build/x86_64-apple-macosx10.10/debug/PerfectCHTTPParser.build/http_parser.c.o
> ld: 4110 duplicate symbols for architecture x86_64
> <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
> error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Volumes/Untitled/SwiftDev/MyApp/.build/debug.yaml main output:

With Kitura, the error looks like this:

> 'CHTTPParser' /Volumes/Untitled/SwiftDev/MyApp/.build/checkouts/CHTTPParser.git-5348291456210268902: error: multiple targets named 'CHTTPParser'

These dependency issues effectively make it impossible to build server-side apps using these frameworks and aws-sdk-swift.

**Comment by jonnymacs** [comment]
Hi @sdnakhla 

There is a branch in development that will compile when added to a vapor project. It needs more testing if you could please try it and provide feedback for your use cases.

This version removes the Prorsum dependency and uses Swift-Nio (synchronous for now) to interface with aws services.

```
.package(url: "https://github.com/GetBlast/aws-sdk-swift-core.git", .branch("swift-nio"))
```

**Comment by jonnymacs** [comment]
@sdnakhla that would be great thank you. I can make a branch of the dynamo module for you that sources core from the swift-nio version if that makes things easier for you?

**Comment by sdnakhla** [comment]
@jonnymacs it should be easy enough for me to fork the DynamoDB repo and change the dependency to test.  I’ll let you know how it goes.

**Comment by jonnymacs** [comment]
@sdnakhla were you ever to able test?

We have merged the upgrade to master and will tag v2 for release in the next week. Please let us know how it goes with your integration.

**Comment by jonnymacs** [comment]
@sdnakhla I will close this issue. The sdk compiles with Vapor, and I would expect it to compile with kitura or perfect as well. Please open another issue if you have problems.
