### ISSUE TITLE
Remove dependency on FoundationXML

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift-core#260]
We currently use FoundationXML when parsing XML payloads. It would be great to remove this dependency since it will dramatically lower the dynamically linked dependencies when running.

Further the new parsing strategy (in a separate package) should be able to operate on `Collection where Collection.Element == UInt8` to further lower our dependency on `Foundation.Data` and reduce the number of copies.

**Comment by fabianfett** [comment]
I'm not sure, but since this should be an implementation detail, we might be able to do this with a minor update?

**Comment by fabianfett** [comment]
Maybe this is of use?

https://github.com/ChimeHQ/Flexer

**Comment by adam-fowler** [comment]
> Maybe this is of use?
> 
> https://github.com/ChimeHQ/Flexer

I have my own string parsing stuff already which could be used https://github.com/adam-fowler/reading but concerned parsing in Swift is going to be way slower than the Foundation C implementations.

**Comment by fabianfett** [comment]
> but concerned parsing in Swift is going to be way slower than the Foundation C implementations.

well the experience from base64 and json thought me something different.

**Comment by adam-fowler** [comment]
We have to support utf8 which would be fun

**Comment by adam-fowler** [comment]
Yep my experience of String is, it is not very fast. There are some functions that are real howlers. They calling `distance` on two indices. It is dreadful.

**Comment by adam-fowler** [comment]
Replaced FoundationXML with Expat
