### ISSUE TITLE
Use swift format to format code

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#270]
Question is which swift format, the [Apple version](https://github.com/apple/swift-format) or [Nick Lockwood's version](https://github.com/nicklockwood/SwiftFormat)?

Obviously the Apple version has official support but Nick Lockwood's version is the one everyone has been using for ever and it has the advantage that we can install it with homebrew. As an aside async-http-client use Nick Lockwoods version.

Maybe add it to sanity.sh and with #269 it'll get run on every PR commit.

**Comment by adam-fowler** [comment]
This is the code from async-http-client `sanity.sh` to run it.
```
printf "=> Checking format... "
FIRST_OUT="$(git status --porcelain)"
swiftformat . > /dev/null 2>&1
SECOND_OUT="$(git status --porcelain)"
if [[ "$FIRST_OUT" != "$SECOND_OUT" ]]; then
  printf "\033[0;31mformatting issues!\033[0m\n"
  git --no-pager diff
  exit 1
else
  printf "\033[0;32mokay.\033[0m\n"
fi
```

**Comment by fabianfett** [comment]
@adam-fowler The Apple Version you linked is something for SourceKit-LSP. ;) I doubt that this could be used for code formatting as is.

> swift-format provides the formatting technology for SourceKit-LSP and the building blocks for doing code formatting transformations.

**Comment by adam-fowler** [comment]
> This package can be used as a command line tool ...
@fabianfett the apple package produces an exe you can run on your source code to format it. So I think we can. I've run it and seen it work.

I actually thought about using it alongside swift-syntax to do the aws sdk swift code generation but swift-syntax looks looked like it had a pretty steep learning curve. Might return to this later.
