### ISSUE TITLE
Add Logger to every operation.

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#274]
Integrate with swift-log and include optional Logger in every operation. With the next release of AsyncHTTPClient we can pass this logger to the HTTPClient. See https://github.com/swift-server/async-http-client/pull/227

Question: What do we want AWSSDKSwift to log?
- [x] Errors returned from AWS
- [x] Warning whenever we don't have credentials
- [x] Info on retrying a failed request
- [x] Info credential updates
- [x] Info credential expiring
- [x] Info on EC2 indicate whether IMSv2 or v1 was used when updating credentials
- [x] Error on syncShutdown

**Comment by fabianfett** [comment]
if a logger is passed and we receive an error, let's log the error (log level error).
we should log warn, whenever we don't have credentials.

**Comment by adam-fowler** [comment]
Info on retries
If AsyncHTTPClient is logging every request we probably don't need to log it as well.
Credential updates, where they were received from, expiring credentials etc

**Comment by fabianfett** [comment]
Replace the print here.

```swift
    deinit {
        // if httpClient was created by AWSClient then it is required to shutdown the httpClient
        if case .createNew = httpClientProvider {
            do {
                try httpClient.syncShutdown()
            } catch {
                print("Error shutting down HTTP client: \(error)")
            }
        }
    }
```
