### ISSUE TITLE
Possible to create potentially malformed URL via object key

### ISSUE THREAD

**Issue by mredig** [swift-aws/aws-sdk-swift-core#284]
**Describe the bug**
`aws-sdk-swift`'s `S3` has a method that calls 
```swift
return client.send(operation: "PutObject", path: "/{Bucket}/{Key+}", httpMethod: "PUT", input: input, on: eventLoop)
```
(amongst other similar calls) that can result in a http url request formed with double slashes when the key starts with a `/`. I don't have an AWS account to confirm that AWS probably doesn't care, but I use Wasabi and it very much does care.

We should get this:
```
https://s3.us-west-1.amazonaws.com/bucketname/path/to/resource.ext
```
but instead we get this:
```
https://s3.us-west-1.amazonaws.com/bucketname//path/to/resource.ext 
```

**To Reproduce**
1. create an object request:
```swift
let objectRequest = S3.PutObjectRequest(bucket: "bucketname", key: "/path/to/resource.ext")
S3().putObject(objectRequest)
//...putObject calls `AWSClient.send`
//...send calls `AWSClient.createAWSRequest`
//... createAWSRequest results in a request with the following:
//request.url.absoluteString = "https://s3.us-west-1.amazonaws.com/bucketname//path/to/resource.ext"
```

**Expected behavior**
We should get this:
```
https://s3.us-west-1.amazonaws.com/bucketname/path/to/resource.ext
```

**Additional context**
I'm not 100% sure this shouldn't be expected behavior, but I thought it was worth notifying anyways. I have a PR ready if this isn't technically a pebkac issue.

**Comment by adam-fowler** [comment]
This only happens when using a custom endpoint so I am closing this one in favour of #285
