### ISSUE TITLE
Possible to create potentially malformed URL via custom endpoint

### ISSUE THREAD

**Issue by mredig** [swift-aws/aws-sdk-swift-core#285]
**Describe the bug**
An `AWSClient` with a custom endpoint doesn't account for the case where an endpoint is provided with a trailing slash.

We should get this:
```
https://s3.wasabisys.com/bucketname/resource.ext
```
but instead we get this:
```
https://s3.wasabisys.com//bucketname/resource.ext
```

**To Reproduce**
1. Create an `AWSClient` with a custom endpoint containing a trailing slash, such as `https://s3.wasabisys.com/`
2. Create a request:
```swift
let request = try client.createAWSRequest(operation: "Test", path: "/{Bucket}/{Key+}", httpMethod: "PUT", input: input)
// request.url.absoluteString = "https://s3.wasabisys.com//bucketname/file.ext"
```

**Expected behavior**
We should get this for the generated url:
```
https://s3.wasabisys.com/bucketname/resource.ext
```

**Additional context**
I'm again not 100% sure that it shouldn't actually behave as it already does and actually allow for double slashes. I would assume it should automatically consolidate them, however.

**Comment by adam-fowler** [comment]
see https://github.com/swift-aws/aws-sdk-swift/pull/307

**Comment by adam-fowler** [comment]
https://github.com/swift-aws/aws-sdk-swift/pull/307 has been merged
