### ISSUE TITLE
flaky test AWSSDKSwiftCoreTests.NIOTSHTTPClientTests testHTTPS

### ISSUE THREAD

**Issue by weissi** [swift-aws/aws-sdk-swift-core#292]
On macOS with NIO master and latest AHC.

```
Test Case '-[AWSSDKSwiftCoreTests.NIOTSHTTPClientTests testHTTPS]' started.
/private/tmp/.nio-release-tools_gpSVyH/aws-sdk-swift-core/Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift:167: error: -[AWSSDKSwiftCoreTests.NIOTSHTTPClientTests testHTTPS] : XCTAssertEqual failed: ("http://httpbin.org/get") is not equal to ("https://httpbin.org/get")
Test Case '-[AWSSDKSwiftCoreTests.NIOTSHTTPClientTests testHTTPS]' failed (1.609 seconds).
```

It also seems that this test may actually reach out to the internet which seems very fragile.

**Comment by adam-fowler** [comment]
Yeah keep meaning to remove that one. We should hopefully be moving to AHC for all platforms when 1.2 is released but until that point we need the internal HTTPClient. 

It was the only way to test HTTPS easily at the time. I'm just going to remove it.

**Comment by adam-fowler** [comment]
done
