### ISSUE TITLE
Tests are not robust to AWS environment variables

### ISSUE THREAD

**Issue by PeterAdams-A** [swift-aws/aws-sdk-swift-core#315]
**Describe the bug**
If you have the environment variable `AWS_DEFAULT_REGION` set to a region other than `us-east-1` some of the unit tests fail.  
The easiest fix is to just unset that variable.

**To Reproduce**
1. `export AWS_DEFAULT_REGION=us-west-2`
2. `swift test`

**Expected behavior**
All tests pass.

**Setup (please complete the following information):**
 - OS: MacOS
 - Version of aws-sdk-swift master as of 30-Jun-2020
 - Authentication mechanism N/A

**Additional context**
It's obvious I can work around this but it would be nice if the tests unset environment themselves so everyone can trivially run them.

**Comment by adam-fowler** [comment]
Thanks for this. Obviously the tests should be more robust. I’ll look into this.

**Comment by adam-fowler** [comment]
This should be fixed now
