### ISSUE TITLE
testMetaDataServiceForECSCredentials fails on macOS

### ISSUE THREAD

**Issue by weissi** [swift-aws/aws-sdk-swift-core#32]
### Expected:

test run

### Actual

```
Test Case '-[AWSSDKSwiftCoreTests.MetaDataServiceTests testMetaDataServiceForECSCredentials]' started.
Fatal error: ERROR: Date conversion failed due to mismatched format.: file /private/tmp/aws-sdk-swift-core/Sources/AWSSDKSwiftCore/MetaDataService.swift, line 193
Exited with signal code 4
```

#### OS

macOS 10.14 pre-release

NB: they do work on Linux

#### Package.resolved

```
{
  "object": {
    "pins": [
      {
        "package": "HypertextApplicationLanguage",
        "repositoryURL": "https://github.com/Yasumoto/HypertextApplicationLanguage.git",
        "state": {
          "branch": null,
          "revision": "2302002502fe573494577cc6e8df686e385519f8",
          "version": "1.1.0"
        }
      },
      {
        "package": "swift-nio",
        "repositoryURL": "https://github.com/apple/swift-nio.git",
        "state": {
          "branch": null,
          "revision": "695afc5205aaa49fca092b94b479ff71c43d9d3c",
          "version": "1.8.0"
        }
      },
      {
        "package": "swift-nio-ssl",
        "repositoryURL": "https://github.com/apple/swift-nio-ssl.git",
        "state": {
          "branch": null,
          "revision": "0adc938bc8de3d3829b842f9767d81c7480b8403",
          "version": "1.1.1"
        }
      },
      {
        "package": "swift-nio-ssl-support",
        "repositoryURL": "https://github.com/apple/swift-nio-ssl-support.git",
        "state": {
          "branch": null,
          "revision": "c02eec4e0e6d351cd092938cf44195a8e669f555",
          "version": "1.0.0"
        }
      },
      {
        "package": "swift-nio-zlib-support",
        "repositoryURL": "https://github.com/apple/swift-nio-zlib-support.git",
        "state": {
          "branch": null,
          "revision": "37760e9a52030bb9011972c5213c3350fa9d41fd",
          "version": "1.0.0"
        }
      }
    ]
  },
  "version": 1
}
```

**Comment by Yasumoto** [comment]
@weissi I couldn't reproduce on 10.13, so took a look at trusty ol' http://nsdateformatter.com.

I plugged in [`2017-12-30T13:22:39Z`](https://github.com/swift-aws/aws-sdk-swift-core/blob/master/Tests/AWSSDKSwiftCoreTests/MetaDataServiceTests.swift#L66) trying to match with [`yyyy-MM-dd'T'HH:mm:ssZ`](https://github.com/swift-aws/aws-sdk-swift-core/blob/master/Sources/AWSSDKSwiftCore/MetaDataService.swift#L190) and that seemed to line up correctly. Although I couldn't find an [official API diff for `Foundation`](https://developer.apple.com/documentation/appkit/appkit_release_notes_for_macos_10.14_beta), I did see [this list](http://codeworkshop.net/objc-diff/sdkdiffs/macos/10.14/) which doesn't seem to show anything _should_ be different.

Generally [AWS uses ISO 8601](https://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html), so I'm posting a diff to use [ISO8601DateFormatter](https://developer.apple.com/documentation/foundation/iso8601dateformatter). If you could give that branch a whirl, that'd be much appreciated!

**Comment by weissi** [comment]
@Yasumoto wow, that's for getting back so quickly, on `yasumoto-dateformatter` the tests all pass!
