### ISSUE TITLE
error: missing required module 'CNIOAtomics'

### ISSUE THREAD

**Issue by EricWVGG** [swift-aws/aws-sdk-swift-core#34]
I was using the https://github.com/swift-aws/s3 package with great success for the past week, then did an update today and got the above message. (reporting here as per my understanding of the relationship between the repos, apologies if this is in the wrong place.)

**Comment by jonnymacs** [comment]
@EricWVGG hi there. yes, this is the right place 👍 

Can you share a bit more about this issue? You were using the s3 sdk then you did an update, how did you perform the update? Did you manually update the s3 Package.swift to pull the 2.0.0-rc.1 version of this package? If so you may need to clean your build dir before compiling.

**Comment by EricWVGG** [comment]
I'm using the Vapor back end framework, so I ran "vapor update" to upgrade some unrelated things. Part of the update process is building a fresh .xcodeproj; once it was finished and I opened it, I couldn't build as per that message.

I did clean and compile several times to no affect.

This was in my package…
`.package(url: "https://github.com/swift-aws/s3.git", .upToNextMajor(from: "1.0.0"))`
…adding this before it fixed things…
`.package(url: "https://github.com/swift-aws/aws-sdk-swift-core", from: "1.0.10"),`

I just removed that to see if I could replicate the problem, but it seems to have gone away. Hope it's a false alarm… I'll close and reopen if it shows up again. 

Thank you, otherwise this library works perfectly, I appreciate it very much.

**Comment by EricWVGG** [comment]
oh, it's back again, I just added a new source file and initiated a rebuild and it showed back up.

**Comment by jonnymacs** [comment]
:D ok, I was nervous when I saw you'd closed it.

Can you share which version of vapor you are using? Is it 2 or 3?

**Comment by EricWVGG** [comment]
Vapor 3. I’m trying to be current and cutting edge with this project :)

**Comment by jonnymacs** [comment]
Thanks Eric.

You might try adding the core sdk version 2 rc1 in your vapor3 package swift.

```
 .package(url: "https://github.com/swift-aws/aws-sdk-swift-core.git", .from("2.0.0-rc.1")),
 .package(url: "https://github.com/swift-aws/s3.git", .from("1.0.0"))
```

I would clear out your build dir and delete your Package.resolved file as well and try to build from scratch.

When that completes

```
vapor xcode
```

and you should have a happy xcode.

**Comment by jonnymacs** [comment]
@EricWVGG any luck trying the above?

**Comment by EricWVGG** [comment]
Initially did not work, and I got distracted and decided to put it aside for a bit. I'll give it another crack tomorrow.

**Comment by Yasumoto** [comment]
Howdy @EricWVGG, any luck? 🤞

**Comment by EricWVGG** [comment]
Not really. I left things alone with the old 1.0.10 dependency and stuff would mostly work. But since Mojave, I can't get a build at all, on any version.

First off, this syntax seems to be wrong…
```
.package(url: "https://github.com/swift-aws/aws-sdk-swift-core.git", .from("2.0.0-rc.1")),
```
Seems to want `from: "x.x.x"` (no period from `from`), or `.upToNextMajor(from: "x.x.x")`

Either way, `vapor build` just stalls out.

**Comment by weissi** [comment]
Just spotted this, @EricWVGG are you building in Xcode by any chance?
I've seen this issue before when SwiftPM-generated Xcode projects get added (as sub-projects) to iOS or macOS GUI apps. Something with the dependencies is not quite right with those SwiftPM-generated Xcode projects when they're used as sub-projects.

@jonnymacs / @Yasumoto I believe today the only way to get a SwiftPM project to reliably work as a sub-project in a regular Xcode project is using CocoaPods at the moment :(. I [did file a SwiftPM bug](https://bugs.swift.org/browse/SR-9024)

**Comment by EricWVGG** [comment]
Yes, it was Xcode.

**Comment by weissi** [comment]
@EricWVGG okay, so just to be clear Xcode itself should  work just fine with if used with the Xcode projects generated by SwiftPM (or through Vapor Toolbox), what causes issues is if these projects are then added as sub-projects to other Xcode projects. Is that what you’re doing?

If you’re not adding one Xcode project to another Xcode project as a sub-project everything should work. If not, try `rm -rf .build Package.resolved *.xcodeproj` and try regenerating the Xcode project using `swift package generate-xcodeproj` or through the vapor toolbox.

**Comment by weissi** [comment]
@EricWVGG / @jonnymacs turns out I was wrong. SwiftPM already implemented everything necessary but NIO's C modules didn't have proper umbrella modules. That's fixed in https://github.com/apple/swift-nio/pull/636 and should be released soon!

**Comment by adam-fowler** [comment]
Closing as this should be resolved.
