### ISSUE TITLE
HTTPClient contains methods that could be imported from NIOFoundationCompat

### ISSUE THREAD

**Issue by weissi** [swift-aws/aws-sdk-swift-core#39]
Just a minor thing: Saw that there's this code

https://github.com/swift-aws/aws-sdk-swift-core/blob/1aa2f17ad20514aefdfd5d780cafd596b2e3b8d7/Sources/AWSSDKSwiftCore/HTTPClient.swift#L38-L76

which appears to just be an old copy of the code in NIO itself. You could just delete that whole extension and put an

    import NIOFoundationCompat

in your files. That way you'll get the recommended `ByteBuffer.readData` as well as the lower level and more sharp-edged tool `ByteBuffer.getData`. [Documentation also available](https://apple.github.io/swift-nio/docs/current/NIOFoundationCompat/Extensions/ByteBuffer.html#/s:3NIO10ByteBufferV19NIOFoundationCompatE9getStringSSSgSi2at_Si6lengthSS10FoundationE8EncodingV8encodingtF).

By the way, `import NIOFoundationCompat` also makes `ByteBuffer.write(bytes: Data)` much faster as it will just to a `memcpy` instead of copying one by one.

**Comment by jonnymacs** [comment]
@weissi :raised_hands:

**Comment by Yasumoto** [comment]
Thanks for the heads up! I don't think those were exported at the time we first made the switch, if I remember right (but could've just been that we didn't know 😄 )

Thanks again!!

**Comment by jonnymacs** [comment]
#40
