### ISSUE TITLE
Shared Credentials override supplied credentials

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#48]
If I have shared credentials on my systems, they are always used regardless of whether I supply credentials to the AWSClient or not. I would have thought it should be the other way where they are used if I don't supply credentials to the AWSClient.

**Comment by jonnymacs** [comment]
@adam-fowler agreed. order should be

`static, env, shared, iam`

**Comment by Yasumoto** [comment]
This is fixed thanks to #51, right?
