### ISSUE TITLE
Remove reliance on libressl and NIOOpenSSL

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#49]
I would like to remove NIOOpenSSL and replace it with NIO Transport Services. This would make it easier to sandbox my application as it wouldn't be dependent on the libressl library and its config files. This all seems ok except AWSSDKSwiftCore makes use of some systems in NIOOpenSSL. Some of these should be easily replaceable with CommonCrypto equivalents but the HTTP client might need a little more work.

I imagine you don't want to make this mac specific but is it possible to make it easier to flip between the new Network.framework and NIOOpenSSL. What are your thoughts?

**Comment by Yasumoto** [comment]
It's [possible to use both `swift-nio-transport-services` and `swift-nio-ssl` in the same project](https://discordapp.com/channels/431917998102675485/448584561845338139/562904496917970965) but for Linux support we'll always need `swift-nio-ssl` at the least.

However, with the new version of `NIOSSL` including `BoringSSL` and removing the system dependency, does that make life better?

If so, we can/should upgrade to `NIO` 2 and the latest version of `swift-nio-ssl`.

I know we need the exported version for the HMAC: https://github.com/swift-aws/aws-sdk-swift-core/blob/master/Sources/AWSSDKSwiftCore/HMAC.swift which we'll need to account for.

Any other examples you know of that we'll need to clear away?

**Comment by adam-fowler** [comment]
Yeah I saw the new version used BoringSSL. This should resolve the issue. Of course if you upgrade you'll have to find alternatives to where you are using CNIOOpenSSL. This includes HMAC code, OpenSSLClientHandler() in HTTPClient and SHA256 and MD5 code in hash.swift.

Upgrading to NIO 2.0 and NIO SSL requires Swift 5 as well.

**Comment by adam-fowler** [comment]
Looking through comments OpenSSLClientHandler() is now NIOSSLClientHandler() and takes a NIOSSLContext as a parameter instead of a SSLContext.

**Comment by adam-fowler** [comment]
All the required HMAC and SHA256 code is in the CNIOBoringSSL framework. Checkout https://github.com/adam-fowler/aws-sdk-swift-core/commits/nio2.0 for changes to get library to compile with NIO 2.0.

**Comment by adam-fowler** [comment]
All the required HMAC and SHA256 code is in the CNIOBoringSSL framework. Checkout https://github.com/adam-fowler/aws-sdk-swift-core/commits/nio2.0 for changes to get library to compile with NIO 2.0.

**Comment by adam-fowler** [comment]
While we wait for NIO2.0 https://github.com/swift-aws/aws-sdk-appleos-core will cover this.
