### ISSUE TITLE
XMLNode reference circle 

### ISSUE THREAD

**Issue by sage444** [swift-aws/aws-sdk-swift-core#60]
Hi there. 
Last week i'm playing with this library and found it really handy. Also I have a lot questions but lets start from trivial ones. 

In `XMLNode` class we have strong references to `parent` and `children` 

```
var parent: XMLNode? = nil
var children = [XMLNode]()
```

So my question is how to properly dealloc this object after use. I believe somebody used this code and may have noticed this leak before.

**Comment by sage444** [comment]
Most obvious fix is to set `parent` as `weak`. 
I would like to submit PR but my fork is broken in several places:)

**Comment by adam-fowler** [comment]
Hi, we’re revisiting the xml encoding in the near future and may be moving to the Foundation XML objects soon along with rewriting the encoder/decoder code path. So this might not be an issue soon.

**Comment by adam-fowler** [comment]
With commit https://github.com/swift-aws/aws-sdk-swift-core/commit/119265d9ffb0be9477cb97db3da30f20f605499b we have removed XMLNode so this is not an issue anymore.
