### ISSUE TITLE
Investigate using swift-server/swift-nio-http-client

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#65]
@Yasumoto suggested we look into replacing the HttpClient we have at the moment with https://github.com/swift-server/swift-nio-http-client. 

We'll need to be on nio2.0 to start this work.

**Comment by Yasumoto** [comment]
Just [finished implementing support for a PagerDuty library I use, and it simplified life a good deal](https://github.com/Yasumoto/PagerDutySwift/blob/master/Sources/PagerDutySwift/PagerDutySwift.swift#L43).

**Comment by adam-fowler** [comment]
@Yasumoto Had a quick look at this and the pain we would have to go through to get it working isn't really worth it. I think if we were starting from scratch it would be a good idea to look into it. 

I did tidy up our HttpClient code so it is more obvious what is happening. Main change being adding a handler for writing data to the channel, instead of doing it a flatMap() on the channel connect() function. You can find it here https://github.com/adam-fowler/aws-sdk-swift-core/blob/httpclient/Sources/AWSSDKSwiftCore/HTTPClient.swift. Changes are applied to the NIO2.0 branch, so haven't created a pull request.

**Comment by adam-fowler** [comment]
With the AWSResponse changes just submitted and my aws-signer lib, integrating this should be a lot easier. My only gotcha at the moment would be it break my iOS builds.

**Comment by adam-fowler** [comment]
Closing this, we can revisit later if async-http-client ever supports NIOTransportServices
