### ISSUE TITLE
Should Shape, Member and Operation.swift be moved out of aws-sdk-swift-core

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#67]
They aren't used in aws-sdk-swift-core, with the exception of the Location enum (which we could move out into its own file). These files are only used in the CodeGenerator. Should they not exist with the CodeGenerator code.

**Comment by Yasumoto** [comment]
100% they should be pulled out. An even more wild idea might be to look into [Sourcery](https://github.com/krzysztofzablocki/Sourcery).

**Comment by adam-fowler** [comment]
include Glob.swift in that as well. 
Sourcery all looks very nice, I'll let you look at that though :-)

**Comment by adam-fowler** [comment]
Sorted https://github.com/swift-aws/aws-sdk-swift-core/commit/d1855942b943711e871a590892c10d2e91b27022
