### ISSUE TITLE
EC2 describeInstances return failure

### ISSUE THREAD

**Issue by hodovani** [swift-aws/aws-sdk-swift-core#90]
In the response to the EC2.describeInstances request I found error:
```swift
failure (
    Swift.DecodingError.dataCorrupted (
        Swift.DecodingError.Context (
            codingPath : [
                CodingKeys (stringValue: "reservationSet", intValue: nil),
                CodingKeys (stringValue: "instancesSet", intValue: nil),
                CodingKeys (stringValue: "platform", intValue: nil)
            ],
            debugDescription : "Cannot initialize PlatformValues from invalid String value windows",
            underlyingError : nil
        )
    )
)
```

The code that fire the issue:
```
    let ec2 = EC2(
        accessKeyId: accessKeyId,
        secretAccessKey: secretAccessKey,
        region: .euwest2
    )
    let instanceRequest = EC2.DescribeInstancesRequest()
    do {
      try ec2.describeInstances(instanceRequest).whenComplete { response in
        do {
            print(response)
        }
      }
    } catch {
      print(error)
    }
```

I got success result when I made same request in the terminal:
`aws ec2 describe-instances`

It might be problem with region, because if I change region to  `.useast1` in swift or in terminal it works correct and return successful result.

Can you please help me?

**Comment by adam-fowler** [comment]
Are you using the 3.0.1 release? Also are you running on macOS or Linux?

**Comment by hodovani** [comment]
@adam-fowler sorry this is issue for AWSSDK AppleOS Core. I created issue in the AWSSDK AppleOS Core.
[link to the issue](https://github.com/swift-aws/aws-sdk-appleos-core/issues/1)
