### ISSUE TITLE
Pass EventLoopGroup down to HTTPClient

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#93]
Currently with every AWS request we create a new EventLoopGroup. Would it be worthwhile to allow the user to pass their own EventLoopGroup in. Perhaps a service could be initialized with an eventloop group and this is used throughout.
```
let s3 = S3(region:.eu-west-1, eventGroup: myEventGroup)
try s3.putObject(...)
```

**Comment by Yasumoto** [comment]
Yep, I think we should. I like the pattern of an [`EventLoopGroupProvider` enum](https://github.com/swift-server/async-http-client/blob/master/Sources/AsyncHTTPClient/HTTPClient.swift#L27), what do you think about this?

**Comment by adam-fowler** [comment]
As long the eventLoop creation is encapsulated in the enum. Without that it just seems like an overengineered optional value.

**Comment by Yasumoto** [comment]
Yes exactly, if provided it's what can be used.

**Comment by adam-fowler** [comment]
@jonnymacs I noticed there is already an eventLoopGroup in the client. Looks like it is used by the MetaDataService. Could we not re-use this for the actual aws http request.

**Comment by adam-fowler** [comment]
Ignore that its a static member of AWSClient

**Comment by adam-fowler** [comment]
Actually don't ignore that. Is there any reason we can't use the static eventGroup variable for all AWS HTTP requests?

**Comment by Yasumoto** [comment]
I think we didn't think to set that at the time; totally a good move to use the `eventLoopGroup` we already have available.

**Comment by adam-fowler** [comment]
This is done #130
