### ISSUE TITLE
Discussion: Remove Package.resolved from repository

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift-core#95]
It's a real pain for development having the Package.resolved file in source control. It is autogenerated so shouldn't need to be included.

If you have a dependency on a branch name you keep having to update the Package.resolved file to get it to build against latest

**Comment by valeriomazzeo** [comment]
I think it's a good idea. As a library, it makes sense for dependencies to be pinned in `Package.swift`.

**Comment by Yasumoto** [comment]
I'm slowly catching up on WWDC videos, and toward the end, [this one](https://developer.apple.com/videos/play/wwdc2019/408) suggests checking in `Package.resolved`. It looks like [there's also some discussion on the forums as well](https://forums.swift.org/t/package-resolved-should-go-in-the-gitignore/14699/13).

I think this advice is mainly for end-users (of an application), the majority of folks who'd run into the `Package.resolved`for this library are likely going to be actively developing this project. There's some value in folks knowing they're all on the same version, but given how active development is (and a few branches in flight) I think making development as easy as possible is wise.

All in all, I support this 👍

**Comment by adam-fowler** [comment]
@Yasumoto Just to be clear when I added this I meant it for aws-sdk-swift. When developing features that use both repositories that is when the Package.resolved gets in the way the most.

I understand the value in ensuring folk are using the same version, but we should be able to edit the Package.swift to ensure that.

**Comment by adam-fowler** [comment]
Package. resolved has been removed from aws-ask-swift and added to the gitignore file
