### ISSUE TITLE
Incorrect encoding for SQS.SendMessageRequest / MessageAttributeValue

### ISSUE THREAD

**Issue by valeriomazzeo** [swift-aws/aws-sdk-swift-core#97]
```swift
SQS.SendMessageRequest(
  messageAttributes: [
    "MyKey": .init(dataType: "String", stringValue: "MyValue")
  ]
)
```

AWS SQS expects something like this to be encoded:
```
Action=SendMessage
&MessageAttribute.1.Name=MyKey
&MessageAttribute.1.Value.StringValue=MyValue
&MessageAttribute.1.Value.DataType=String
```

`AWSShapeEncoder` is instead producing this:
```
Action=SendMessage
&MessageAttribute.entry.1.key=MyKey
&MessageAttribute.entry.1.value.StringValue=MyValue
&MessageAttribute.entry.1.value.DataType=String
```

Patching `AWSShapeEncoder.swift` line 66 fixes the issue:

Removing:
```swift
                case let v as [AnyHashable : AWSShape]:
                    var entryString = "entry"
                    var keyString = "key"
                    var valueString = "value"
```

Adding (note they **must** be capital case):
```swift
                case let v as [AnyHashable : AWSShape]:
                    var entryString = ""
                    var keyString = "Name"
                    var valueString = "Value"
```

I don't know whether this affects only SQS or also other services.
@adam-fowler thoughts?

**Comment by adam-fowler** [comment]
Again are you using HEAD or version 3.0.1. A lot of work has gone into resolving these issues recently.

**Comment by valeriomazzeo** [comment]
@adam-fowler I am using your branch here https://github.com/swift-aws/aws-sdk-swift-core/pull/96 so yes, that's pretty much similar to `master`.

**Comment by adam-fowler** [comment]
Are you running with master from aws-sdk-swift as well? I have added encoding hints to each service AWSShape classes which tell the core code how to serialize arrays and dictionaries.

**Comment by valeriomazzeo** [comment]
Tried on both repositories `HEAD` and you are right - encoding seems to be correct.

Although, I can't manage to point to both:
- `HEAD` for https://github.com/swift-aws/aws-sdk-swift.git
-  https://github.com/swift-aws/aws-sdk-swift-core/pull/96 for https://github.com/adam-fowler/aws-sdk-swift-core.git

So it looks like I am stuck until that PR is merged in.

**Comment by adam-fowler** [comment]
Yeah well hopefully we'll get a release out soon, which would make things a little easier
